spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.jdbc.Driver       # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/graduation_project           # 数据库连接地址
    username: root                                  # 数据库用户名
    password: 123456


mybatis:
  type-aliases-package: com.cqnu.purchasedao.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml


#整合mybatis


